### ISSUE TITLE
[Feature Request] Add Hotkey for + Add a list 

### ISSUE THREAD

**Issue by Obadiahcruz** [mgmeyers/obsidian-kanban#159]

**Comment by Obadiahcruz** [comment]
Have you thought about adding a hotkey for adding a new list? would save time from not need to use a mouse when first creating a kanban board and adding multiple lists

**Comment by pjeby** [comment]
After playing around with Speare (after seeing it on the roadmap), I find myself wanting to use the Kanban plugin that way, because the whole "open up a new lane and keep going, you can always drag it somewhere else later" is great for free flowing.  If there's a keyboard command to add a list, ideally it should also open and focus the new list's add box, so that you can "change lanes" easily.

One possibility: make the tab key be "next lane" and mod-tab be "insert lane right", with shift reversing direction.  The lane could initially be untitled, and the card context menu could allow setting the title from an item (or it could just default to making the list title the same as the first item, ala Speare).

I guess what I'm saying is, is that it's useful to have a command that adds a list and asks for the title next, but it would also be useful to have a low-impact way of changing or adding lanes that *doesn't* require you to set a list title first.

Last, but not least: I think creating or opening an empty kanbans should auto-add an "Untitled" list and focus its add-item box, so that you can begin capturing ideas immediately without taking hands off the keyboard.  (i.e. hit "new kanban" or "blank to kanban" command and then just start typing).

**Comment by mgmeyers** [comment]
@Obadiahcruz I've added a command to open the lane form 

<img width="723" alt="Screen Shot 2021-09-25 at 6 12 54 PM" src="https://user-images.githubusercontent.com/2694747/134789781-7cf30a2d-3400-4199-b0be-2189580b5441.png">
