### ISSUE TITLE
Error when swapping items between the same board open in two panes

### ISSUE THREAD

**Issue by mgmeyers** [mgmeyers/obsidian-kanban#172]
https://discord.com/channels/686053708261228577/707816848615407697/851362453791178752

pjeby says:
> It might be possible to fix that by having only one board object per file internally, rather than one per view.

**Comment by pjeby** [comment]
A possible fast fix would be to stop using `requestSave()` and use `save()` instead.  The issue is that if you modify the board in one view, then in the other within 1s, one of the views will enter reconciliation, i.e. it goes, "you have dirty data that hasn't been saved, but we just saw a save from the other window, so imma combine that with what you're doing", and boom!

A better long-term fix would probably be to stop using setViewData as the means for loading data, and instead just reading straight from the file whenever it's modified or when the target file changes.

An intermediate fix would be for the view to emit `quick-preview` events on board changes, and take in the data from them as well.  This would ensure all boards would synchronize state, and incidentally make the word counter live while editing the board.  :grin:  It also *should* prevent the reconciliation, though I think there are some details to be figured out (i.e. reverse engineered from Obsidian internals.  :frowning_face:)
