### ISSUE TITLE
Refactor to prevent unnecessary rerenders / improve perf

### ISSUE THREAD

**Issue by mgmeyers** [mgmeyers/obsidian-kanban#185]
- Utilize memoing and useCallback
- Be careful who uses context
- De-couple board from board modifiers

**Comment by pjeby** [comment]
See also #190 for my current plans.  I've laid the groundwork there for replacing board modifiers with mutator funcs, i.e. you'll just pass setBoardData down instead, and give it a function as a param (e.g.  `setBoardData(addLane(lane))`, if addLane has a type of `addLane: (b: Board) => Board`.  That should allow basically anything to be done from anywhere, without requiring centralized knowledge of all possible update operations (as is currently the case).

**Comment by pjeby** [comment]
Also worth looking at: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/virtual-lists.md

The ["board" demo](https://react-beautiful-dnd.netlify.app/?path=/story/virtual-react-virtualized--board) shows it is possible to do Trello-like columns with rb-dnd, as well as virtualized rendering with react-virtualize.   And the demo handles two auto scroll directions just fine, so I'm not sure why it says it can't handle multiple scroll directions?  Anyway, something to look into.

(Also, ran across [dnd-kit](https://docs.dndkit.com/presets/sortable#architecture) that does keyboard nav and autoscroll and a few other things, though it might need "real" react rather than preact.)

In my work on #199, I found that it's *much* easier to get component classes to avoid repeat renders than it is for complex function components.  After figuring that out myself, I ran across [this guide](https://ntsim.uk/posts/optimizing-react-component-event-handlers) I wish I'd seen before now.  Basically, you just make your event handlers bound methods on your Component instance, and use those as event handlers.  No need for useCallback or memos or anything else.

So I made MarkdownRenderer a class that keeps track of state for search and reuses the same DOM objects instead of setting inner HTML.  AFAICT initial board rendering seems faster, while search and updates seem about the same.  A lot of time is still spent in re-rendering components, though, and markdown-to-HTML rendering is the biggest time guzzler other than that.  Even with my best optimizations so far, my test board of ~220 items still takes 1.5 seconds to fully load in the *best* case (and often takes 2 seconds).  For what the plugin is doing, that still seems insanely slow to me, even though that's an improvement over the usually 2-to-4 seconds that it was before I started tweaking things.

However, as a sanity check, I tried disabling markdown HTML conversion altogether, just skipping the Obsidian render call and instead jamming innerText in a div (so the other code wouldn't change) and got the timing down to less than a second in the best case.  That suggests that some combination of virtualization and/or async rendering should ultimately do the trick, as skipping HTML shaves 300ms off the parse time and a bunch more off the render/style/layout/reflow process.  (This is how Obsidian itself manages to avoid these things: its preview windows only render the amount that fits the frame to start with.)

I will probably do some more experiments later, see if converting the Item components to classes with event handler methods will do the trick to drop the excess rendering overhead on board changes.  Sadly there's probably nothing short of virtualization that will keep the initial load down, but then I've been surprised by this codebase before.  :grinning:

**Comment by pjeby** [comment]
Like just now, where I realized I hadn't done anything about the "make an Obsidian menu object for every item on the board, on every render" problem.  :wink:  Just checked that in, brings the average initial render time for my test board down to <1s...  almost as good as dropping markdown->html conversion!  So that's a big step forward.  I would guess that that was the most expensive thing any of the components are doing on *initial* render though, that isn't related to the markdown rendering.  For *re*-rendering there is probably still a lot of room for tune-up, e.g. by switching the most common components (i.e. per-Item components) to be class components with event handler bound methods.  Search is still painfully slow on my large board, too.

**Comment by mgmeyers** [comment]
> The ["board" demo](https://react-beautiful-dnd.netlify.app/?path=/story/virtual-react-virtualized--board) shows it is possible to do Trello-like columns with rb-dnd, as well as virtualized rendering with react-virtualize. And the demo handles two auto scroll directions just fine, so I'm not sure why it says it can't handle multiple scroll directions? Anyway, something to look into.

FYI on this: the problem arises when there are two nested scroll containers (that are not the body element), which is the case for the kanban board. Eg. there's the `.view-content` element and if we were to cap the height, the `.kanban-plugin__lane-items` elements.

**Comment by pjeby** [comment]
I don't understand...  how does that demo work, then?  Hm.  Looks like it's an iframe.  Does that mean if we made the content element into an iframe, it would work?  ;-)  [This answer](https://stackoverflow.com/a/34744946) suggests you can mount portals in iframes, so we could render into the iframe.  But I guess then we'd lose dragging between panes, if it won't let you drag outside the window then.  Ah well.

(Interesting thought... I just found some demos of react rendering into other windows via portal...  which would be freaking awesome, if only Obsidian were configured to use nativeWindowOpen.  Then we could just put each board in its own window.  :grin:)

**Comment by pjeby** [comment]
So, I found one source for why every card gets rerendered on every change: KanbanContext.  Every `useContext` forces a re-render when the context object changes.  And every card uses the KanbanContext.  And the KanbanContext has the board in it, so it changes every time *any* change to the board happens, no matter how small.  (I think it recreates the boardModifiers, too.)

So the next step looks like seeing if I can ditch KanbanContext, or at least make the boardModifiers a constant, and fix things so only boardModifiers and the top-level component need access to the board itself.

**Comment by mgmeyers** [comment]
Yeah, I figured. That's what I was thinking with these: 

> Be careful who uses context
> De-couple board from board modifiers

https://github.com/mgmeyers/obsidian-kanban/issues/185

Context can be very helpful, but I built most of this knowing I would have to come back and optimize for performance. If we could separate the modifiers from the board and prevent them from ever changing, that would go a long way for perf.

**Comment by mgmeyers** [comment]
Now that we're using `dataBridge.useState`, it seems we could freely pass around the `setBoardData` function, which shouldn't change. Maybe that can get its own context. We could then do `setBoardData(oldData => update(oldData, ....))`

**Comment by mgmeyers** [comment]
Also, doing what I did here is an antipattern: 

https://github.com/mgmeyers/obsidian-kanban/blob/main/src/components/Kanban.tsx#L407-L408

```
    <ObsidianContext.Provider value={{ filePath, view }}>
      <KanbanContext.Provider value={{ boardModifiers, board: boardData }}>
        <SearchContext.Provider
          value={{ query: searchQuery.toLocaleLowerCase() }}
        >
```

Each time the Kanban renders, it creates a new object for each of these `values`, thus causing any context consumers to update.

**Comment by pjeby** [comment]
In the PR, boardModifiers are immutable and use setstate reducer functions.  There's also only one context now to rule them all.  :wink:  It does mean the boardModifiers change when the search query does, but the truth is that every item gets re-rendered by the search query anyway, so a full refresh isn't a big deal there.  It might be good to debounce the search query updating from the text input, though, as there can be a big lag between you typing and what you typed showing up.

Anyway, the main remaining stuff as far as perf goes at this point is basically event handlers and other "it's different every time" things.  Some of those could be done with useCallback, but Component class methods might have better performance.  Everything on your list is, I think, already taken care of in the PR.  Once the remaining re-render fixes are done, the only way to get any further performance upgrades would probably come from virtualizing.  (Especially for initial load times, which are still around 1 second for 200 items, with maybe 1/3 of that being markdown->html processing and the rest being rendering.)

**Comment by pjeby** [comment]
At this point, the performance is pretty good, and the dominant performance hit is GC causing the UI thread to block and thus freeze the display until it catches up.  To avoid closure creation and discarding, it would likely require essentially everything above items (i.e. board and lane) becoming PureComponent and using methods in place of passing down event handlers.

Upon reflection, the ultimate cause of this is that the data model is a single immutable Board state whose contents are passed down to all the child components as props, rather than managed as state at a tree-appropriate level.  While this keeps the data model simple, it enforces a requirement for all of an item's parent components to re-render.

In contrast, consider a data model where the board sees a list of lane IDs, and lanes see lists of item IDs, and in each case the lower level components initialize their state from data provided by the context, registering themselves for state updates.  In such a model, the board would not update for an item change, nor would any lanes, so using functional components would be fine.  Conceptually, you would have a database/event system in the context that things would register for, so that changes only re-render the relevant portion of the tree.

In that model, you could safely use functional components, though I still do think that Item and MarkdownRenderer at least have very good cause for staying classes and thus avoiding creation and discarding of closures on every keystroke.  (At least once Item is fixed up that way; I didn't move all its callbacks to methods yet, as the immediate goal was just to keep from having *every item in the lane* updating on every keystroke!)

But of course, such an event-based data model would add its own form of complexity.  It would largely have to be done outside the React tree, but then it could perhaps be shared across views at the plugin level, which would allow bypassing quick preview and having even faster updates to multiple views.

Anyway, I guess the point is that while functional components avoid one kind of complexity, dealing with the perf issues creates another, so it's kind of a choice as to where you want to put the complexity?  I suppose a board differ/event provider thingy wouldn't be *that* complex, certainly not more complex than the parser now is, anyway.  :wink:  So, up to you where you want to go with that.

Within the current model, there is definitely still some room for specific improvements, like finishing the PureComponent for Item so that it doesn't create closures per render, and doesn't update just because the item has been moved up or down or side-to-side.  It would be nice if initial board rendering could be faster, too, but I don't really have any ideas on how to do that.
