### ISSUE TITLE
Invariant violation when dragging in a single board.

### ISSUE THREAD

**Issue by mgmeyers** [mgmeyers/obsidian-kanban#204]
@pjeby 

Seems like the droppable id is changing during drag. This may be a non-issue after the switch to react-dnd (probably best to focus on that).

https://user-images.githubusercontent.com/2694747/122135100-b65a0800-cdf4-11eb-8ffb-ede694e1ea44.mov

**Comment by pjeby** [comment]
A little confused about the metadata part of that commit -- the metadata invalidation in the parser wasn't handling that?  All it should do is cause metadata to be refreshed on the items, or so I thought.

**Comment by mgmeyers** [comment]
Yeah, not too sure what's going on here, but it seems the entire board was updating and some IDs were changing. Need to dit into it some more to see what the real culprit was.

**Comment by pjeby** [comment]
A current limitation of the parser is that it currently can't preserve column ids if the board changes too much.  If only one line changes, it can just update the one item and keep all lane objects with same IDs.  But if you move items around in a column or between columns it keeps the item IDs but not the lane IDs.

That shouldn't affect metadata updates, though -- if a file's metadata changes then the reparse should keep the same item IDs and lane IDs, as long as settings weren't also changed.  That's why I was a bit confused about this change, as it looks like it should be redundant to what the parser is already doing, while not actually improving on any of the parser's current limitations.  (Unless I've missed something and there's a bug in the parser I didn't notice?)
