### ISSUE TITLE
[Feature]: Paste file into card title

### ISSUE THREAD

**Issue by Quorafind** [mgmeyers/obsidian-kanban#326]
### Goal or desired outcome of this feature

I wanted to paste file into card title.

### Describe the feature

1. Open input box and then paste file in the clipboard into title.

### Can you think of any alternatives or work-arounds?

I don't think so.

### Screenshots, mockups, or videos

![image](https://user-images.githubusercontent.com/13215013/135369305-2db5448d-8b24-4fb7-aa15-6c591f5ae2fb.png)

**Comment by mgmeyers** [comment]
@Quorafind Can you clarify what you mean here? Pasting seems to work fine for me. What happens when you try to paste?

**Comment by Quorafind** [comment]
@mgmeyers Sorry, I tried and then I think it should correct to paste a pic/other file into card.

**Comment by mgmeyers** [comment]
@Quorafind I have some unfortunate news on this one. I investigated this a bit and found out that for the most part this isn't possible due to Electron.js limitations. Pasting images works sometimes, but not reliably. I'll keep an eye out for work arounds, but I'm going to close this issue out for now.
