### ISSUE TITLE
[Bug] Cannot shift + enter to create new line

### ISSUE THREAD

**Issue by ryadaj** [mgmeyers/obsidian-kanban#440]
Hi! Loving this plugin and have been using for a while. 

Actually, I raised this issue many months ago in discord but we were not able to resolve. Since then, I replaced my computer (and keyboard) and wasn't using kanban for a while because I didn't need to but I'm using it again and find that I still can't create a new line in cards.

Here is more detail:
- `shift + enter` does not create a new line, `enter` on its own completes the card
- when changing new line trigger to just `enter` I can create a new line, but `shift + enter` does not complete the card
- I have tried this without a theme selected, and using both Live Preview and legacy editor
- I am a Mac user

Let me know what other info you might need.

Thanks!

**Comment by davebhc71** [comment]
Just installed the plugin to iPad Air. Having the EXACT same issue as above. Apparently this hasn’t been fixed OR at least no comment was provided by the Dev. Anyone have a comment…or has development of this plugin ceased. Not a good look that one has to search and find the issue was posted 3 months ago with no solution.

**Comment by mgmeyers** [comment]
@davebhc71 While I understand your frustration, please understand that obsidian-kanban is free software that I invest my free time building. While I receive some generous donations to maintain this and several other obsidian plugins, I don't receive enough for these plugins to be my primary job (alongside grad school). And they take a lot of time to build, and it takes a lot of time to regularly report on the status of every issue filed. So it's only natural that bugs are going to exist in this plugin, and issues are going to remain un-responded to.

If you're worried that plugin development has ceased, you can follow the development activity here: https://github.com/mgmeyers/obsidian-kanban/pulse

If you'd like to fund the plugin for more active development, that can be arranged to. Just let me know.

**Comment by davebhc71** [comment]
Matthew - thank you for the timely response. I understand and empathize with your explanation. However, I would suggest that if possible it might be beneficial to a new user (and possible Patron) if there was a list of Known Issues somewhere n your GitHub (aside from searching open Bug reports) especially if the issue is with Desktop or Mobile. I would like nothing better than to support a Plugin (or Theme……think Minimal) that offers value to my use of Obsidian. If fact, I have and do regularly support several for just that reason. I would be more than happy to include you in that ‘coffee club’….when your plugin works for me.
Regards,
Dave B

**Comment by mgmeyers** [comment]
@ryadaj Can you go here and press shift + enter? https://keycode.info/

There should be a box that looks like this:

<img width="352" alt="Screen Shot 2022-04-02 at 11 46 00 AM" src="https://user-images.githubusercontent.com/2694747/161397048-46317627-c540-4cf5-8dbc-18c1d65b37ed.png">

Could you send me a screenshot of that?

**Comment by davebhc71** [comment]
I’m using an iPad with Keyboard Folder-

**Comment by ryadaj** [comment]
@mgmeyers here is the screen shot.
<img width="1580" alt="Screen Shot 2022-04-03 at 13 27 57" src="https://user-images.githubusercontent.com/82765301/161440342-fe680849-ed9f-4796-b066-2519d82aaade.png">

**Comment by ryadaj** [comment]
@mgmeyers for some reason this is no longer not working so please feel free to close
