### ISSUE TITLE
[Bug]: Cannot set card font size to custom value

### ISSUE THREAD

**Issue by teake** [mgmeyers/obsidian-kanban#489]
### Describe the bug

I cannot set the font size to a custom value via a CSS snippet.

### Steps to reproduce

I'm having trouble setting the font size of cars to a custom value. In a CSS snippet, I've tried setting `font-size` for the following:

* `.kanban-plugin__markdown-preview-view`
* `.kanban-plugin__item`

Those did not have the desired effect. Setting `font-size` for `.kanban-plugin__item-input` does work though, but then only the "edit mode" has a different font size. Any help on setting the card font size in the markdown preview view would be greatly appreciated!

I'm using the [Minimal](theme) theme version 5.1.5, kanban 1.2.29, obsidian 0.13.33.

### Operating system

macOS

**Comment by mgmeyers** [comment]
Hi @teake it looks like this is a minimal theme issues. It sets the font-size here: https://github.com/kepano/obsidian-minimal/blob/master/src/scss/plugins/kanban.scss#L34-L40

So you'd probably have to use `body .kanban-plugin__markdown-preview-view` to override the theme styles. Let me know if you have any issues with this!

**Comment by teake** [comment]
Ah, turns out `body .kanban-plugin__item-title p` lets me adjust the font size of the cards. Thanks for pointing me in the right direction!

**Comment by Doc-98** [comment]
I think this could be very usefull on the documentation page, seen as how popular the theme is and how difficult is this information to find.

I just spent almost 2 hours to fix the same problem as op and I had to manually come here and search "font size" in the issue page. This page doesn't seem to be picked up easly.

I just added this to my snippet file:

```
//KANBAN BOARD HEADINGS FONT SIZE
body .kanban-plugin__markdown-preview-view {
  font-size: 20px !important;
}
//KANBAN BOARD NORMAL TEXT FONT SIZE
body .kanban-plugin__item-title p {
  font-size: 20px !important;
}
```
This is because (at least atm) the font size is treated differently for headings and normal text.

Hope this helps.
