### ISSUE TITLE
Feature request: embed images

### ISSUE THREAD

**Issue by Scarlov** [mgmeyers/obsidian-kanban#49]
An ability to embed images into the cards of the board.

**Comment by danraymond** [comment]
I second this - simply imgae inclusion would be fantastic.

**Comment by pjeby** [comment]
Just an FYI, external images work if you use `![](https://whatever...)` syntax, or even using `app://local/...` paths to reference local files.  I'm just not sure why regular embedding (i.e. `![[Something.png]]`) doesn't work, when `![](app://local/path/to/vault/Something.png)` does...

Aha! It's because preview mode does delayed image loading for internal link embeds, and at the time when the Kanban plugin copies the HTML, the image isn't loaded yet.  This would probably be resolved by mounting the markdown preview DOM into the card, which should then allow support for anything that markdown preview supports normally.

**Comment by pjeby** [comment]
Ugh.  I spoke too soon...  a little investigation reveals that even if you don't copy the HTML, the handlers and embed-loading still don't run; which is apparently a [known issue](https://github.com/obsidianmd/obsidian-api/issues/11).  So until that upstream issue is resolved, the only working way to embed images is with `file:///`, `app://local/`, or `http` URLs.

**Comment by danraymond** [comment]
Noticed that if I do the app://local.... it displays in the editor (using
the image in editor plugin) but does not render in preview mode

**Comment by pjeby** [comment]
It works fine for me with with either file: or app://local; do note that for external URLs like these you have to use markdown standard syntax, i.e. `![](file:///...)` or `![](app://local/...)`.  The wikilink (`[[ ]]`) syntax is for internal links only.

**Comment by skillhacker-code** [comment]
Yes image inclusion would be awesome

**Comment by pjeby** [comment]
So, in the DOM this plugin converts to HTML, there will be some elements matching `.internal-embed` (either span or div, depending on the syntax used for the image -- Obsidian style makes a span, Markdown style a div) with a `src` and (optional) `alt` set.  The `src` is a link that can be resolved, and the file extension checked for image-ness, and the span or div replaced with an `img` element using the `vault.getResourcePath()` as its `src`.  That would enable images, at any rate; embeds of notes could be replaced with a link, I suppose.

**Comment by pjeby** [comment]
I think this can be closed now, as `![[ ]]` and `![]( )` both work to embed internal images now, and you can even set the size.
