### ISSUE TITLE
[Bug]: Coloured tags not working

### ISSUE THREAD

**Issue by ArthurPKFX** [mgmeyers/obsidian-kanban#776]
### Describe the bug

Adding coloured tags to the plugin or kanban's settings doesn't actually colour the tags

### Steps to reproduce

Create new kanban, create list, create card with tag in title. Go to settings (either kanban or plugin), add tag color. Doesn't get colored

### Operating system

Windows 10

### System
Using Obsidian 1.2.7
Using Kanban 1.5.2
Some community plugins enabled, behaviour is the same without them
Some core plugins enabled, can send the complete list

**Comment by ArthurPKFX** [comment]
Found the issue. The naming put as the key in the setting should include the hashtag of the tag. I personally think that's a bug but at least I now have coloured tags!
Thanks for all the great work, this is by far the best productivity booster I've found so far

**Comment by ArthurPKFX** [comment]
Make sure to use `#low` instead of `low` in the `Tag` field for entries in `Display tag colors`, basically

**Comment by baderk** [comment]
I think it's a bug as in it should be clear in the **default tags**. They should be i.e. "#To-do" instead of "To-do". Showing a default setting should not be incorrect. I know a tag naturally starts with "#", but I thought with this plugin you get to have both options, especially when you first look at this:

<img width="212" alt="Screenshot 2023-12-23 at 9 23 36 PM" src="https://github.com/mgmeyers/obsidian-kanban/assets/10656279/3d4222b8-aa02-43df-b3b2-ef90bbc864c9">

And that's why I'm here, I was looking to see if I'm missing anything because they work with "#" but not without. It's just a bit misleading I would say.
